### ISSUE TITLE
可不可以搞一下一键部署

### ISSUE THREAD

**Issue by tutuxka** [mblog-backend/backend#12]
可以搞一下一键部署，这样可以在replit上部署，也可以编译打包好吗，上手既用，谢谢

**Comment by kingwrcy** [comment]
[它来了](https://replit.com/@kingwrcy/mblog-backend?v=1)

点击上面链接一键部署.

@tutuxka 试试吧.

部署完成后默认用户名/密码: `admin/a123456`
